[package]
name = "coruscant-world"
version = "0.0.0"
authors = ["luojia65 <me@luojia.cc>"]
edition = "2018"

[dependencies]
coruscant-nbt = { version = "0.1", path = "../coruscant-nbt" }
serde = { version = "1.0", features = ["derive"] }
